import globalSettings from './globalSettings'
import products from './products'
import richText from './richText'
import FAQ from './faq'
import category from './category'
import features from './features'
import product_reviews from './product_reviews'
import staticPages from './static'
import product_type from './product_type'
import product_brand from './product_brand'
import posts from './blog/posts'
import blogCategory from './blog/blogCategory'
import author from './blog/author'

export const schemaTypes = [globalSettings, products, FAQ, richText, category, features, product_reviews, staticPages, product_type, product_brand, posts, blogCategory, author]
